services:
  db:
    image: postgres:13
    container_name: onecost_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: onecost
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
    container_name: onecost_backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always

  dashboard:
    build:
      context: ./dashboard
    container_name: onecost_dashboard
    volumes:
      - ./dashboard/src:/app/src
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:

