FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client dos2unix python3-dotenv --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY ./backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./backend/entrypoint.sh /app/entrypoint.sh
COPY ./backend /app

RUN mkdir -p /srv && ln -sfn /app /srv/backend
RUN dos2unix /app/entrypoint.sh && chmod +x /app/entrypoint.sh
RUN test -f /app/entrypoint.sh && test -f /app/server.py

ENV APP_DIR=/app
ENV COMPROVANTES_STATIC_DIR=/app/static/comprovantes

ENTRYPOINT ["/bin/sh", "/app/entrypoint.sh"]
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
