FROM python:3.9-slim

WORKDIR /srv/backend

RUN apt-get update && apt-get install -y postgresql-client dos2unix python3-dotenv --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY ./backend/requirements.txt /srv/backend/requirements.txt
RUN pip install --no-cache-dir -r /srv/backend/requirements.txt

COPY ./backend/entrypoint.sh /srv/backend/entrypoint.sh
COPY ./backend /srv/backend

RUN dos2unix /srv/backend/entrypoint.sh && chmod +x /srv/backend/entrypoint.sh
RUN test -f /srv/backend/entrypoint.sh && test -f /srv/backend/server.py

ENV APP_DIR=/srv/backend
ENV COMPROVANTES_STATIC_DIR=/srv/backend/static/comprovantes

ENTRYPOINT ["/bin/sh", "/srv/backend/entrypoint.sh"]
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
